### PR TITLE
Initial deployment

### PR DESCRIPTION
**Pull request by wuehr1999**
Hi @aentinger,
this PR will is the initial software deployment solution. 
To fulfill the task, I ask You to provide startup scripts for every desired tmux window in
- ```robot/ws/run/script```: Shell scripts, e. g. for setting up CAN drivers
- ```robot/ws/run/launch```: ROS launch files

### CODE REVIEW

**Comment by aentinger** [comment]
Hi @wuehr1999 :coffee: :wave:

Thank you for preparing this, I shall fill it in the next couple of days ;)

**Comment by aentinger** [comment]
>ROS launch files

I'm mostly using the launch files directly stored within the repositories. Shall I provide a symbolic link? Or should I rather provide a textual list (here) of which launch file is to be used within each repository and you'll encoded that into the docker-software-image?

**Comment by wuehr1999** [comment]
Hi @aentinger a relative symbolic link would be a good solution.

**Comment by aentinger** [comment]
Hi @wuehr1999 :coffee: :wave: 

I've added the scripts/launch files in question. What I was wondering about ... is it really necessary to keep the launch-files/scripts in those separate directories? I am asking, since they are made available ("installed") when running `. install/setup.bash` in the workspace root directory.

Note: for invoking the `setup_can.sh` script, consider using such structure as shown below:
```bash
if ! [ -e /sys/class/net/can0 ]; then
    sudo ./setup_slcan.sh --remove-all --basename can --speed-code 5 /dev/serial/by-id/usb-Zubax*Babel*
fi
```

**Comment by wuehr1999** [comment]
Hi @aentinger, in my opinion a launch file is specific for a platform and should not be stored in the node repository directly.

**Comment by aentinger** [comment]
I'd say it depends. If its a special ROS package such as `l3xz_gait_ctrl` or a more generalized one such as `ros2_dynamixel_bridge`.

**Pull request merged**
